# 离线安装 haproxy
- name: 准备离线安装包目录
  file: name=/opt/kube/packages/haproxy state=directory

# 飞腾麒麟 4.0.2
- block:
  - name: 分发 haproxy_juniper_ft_Kylin 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_juniper_arm64.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_juniper_arm64.tar.gz"

  - name: 安装 haproxy_juniper_ft_Kylin 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_juniper_arm64.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when: ansible_distribution_release == "juniper"
  ignore_errors: true

# 统信UOS
- block:
  - name: 分发 haproxy_eagle_uos 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_uos_arm64.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_uos_arm64.tar.gz"

  - name: 安装 haproxy_eagle_uos 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_uos_arm64.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "20"'
  - 'ansible_distribution_release == "eagle"'
  - 'ansible_architecture == "aarch64"'
  ignore_errors: true

- block:
  - name: 分发 haproxy_xenial 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_xenial.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_xenial.tar.gz"

  - name: 安装 haproxy_xenial 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_xenial.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when: ansible_distribution_release == "xenial"
  ignore_errors: true

- block:
  - name: 分发 haproxy_bionic 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_bionic.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_bionic.tar.gz"

  - name: 安装 haproxy_bionic 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_bionic.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when: ansible_distribution_release == "bionic"
  ignore_errors: true

- block:
  - name: 分发 haproxy_centos7 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_centos7.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_centos7.tar.gz"

  - name: 安装 haproxy_centos7 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_centos7.tar.gz && \
           rpm -Uvh --force --nodeps *.rpm > /tmp/install_haproxy.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "7"'
  - 'ansible_distribution_release == "Core"'
  - 'ansible_distribution == "CentOS"'
  ignore_errors: true

# 中标麒麟 And CentOS7_arm64
- block:
  - name: 分发 haproxy_centos7_arm64 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_centos7_arm64.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_centos7_arm64.tar.gz"

  - name: 安装 haproxy_centos7_arm64 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_centos7_arm64.tar.gz && \
           rpm -Uvh --force --nodeps *.rpm > /tmp/install_haproxy.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "7"'
  - 'ansible_distribution_release in ["AltArch","Maipo"]'
  - 'ansible_distribution in ["CentOS","RedHat"]'
  ignore_errors: true

- block:
  - name: 分发 haproxy_stretch 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_stretch.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_stretch.tar.gz"

  - name: 安装 haproxy_stretch 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_stretch.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when: ansible_distribution_release == "stretch"
  ignore_errors: true

- block:
  - name: 分发 haproxy_buster 离线包
    copy:
      src: "{{ base_dir }}/packages/haproxy_buster.tar.gz"
      dest: "/opt/kube/packages/haproxy/haproxy_buster.tar.gz"

  - name: 安装 haproxy_buster 离线包
    shell: 'cd /opt/kube/packages/haproxy && tar zxf haproxy_buster.tar.gz && \
           dpkg -i *.deb > /tmp/install_haproxy.log 2>&1'
  when: ansible_distribution_release == "buster"
  ignore_errors: true

# 离线安装 keepalived
- name: 准备离线安装包目录
  file: name=/opt/kube/packages/keepalived state=directory

# 飞腾麒麟 4.0.2
- block:
  - name: 分发 keepalived_juniper_ft_Kylin 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_juniper_arm64.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_juniper_arm64.tar.gz"

  - name: 安装 keepalived_juniper_ft_Kylin 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_juniper_arm64.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when: ansible_distribution_release == "juniper"
  ignore_errors: true

# 统信UOS
- block:
  - name: 分发 keepalived_eagle_uos 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_uos_arm64.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_uos_arm64.tar.gz"

  - name: 安装 keepalived_eagle_uos 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_uos_arm64.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "20"'
  - 'ansible_distribution_release == "eagle"'
  - 'ansible_architecture == "aarch64"'
  ignore_errors: true

- block:
  - name: 分发 keepalived_xenial 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_xenial.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_xenial.tar.gz"

  - name: 安装 keepalived_xenial 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_xenial.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when: ansible_distribution_release == "xenial"
  ignore_errors: true

- block:
  - name: 分发 keepalived_bionic 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_bionic.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_bionic.tar.gz"

  - name: 安装 keepalived_bionic 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_bionic.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when: ansible_distribution_release == "bionic"
  ignore_errors: true

- block:
  - name: 分发 keepalived_centos7 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_centos7.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_centos7.tar.gz"

  - name: 安装 keepalived_centos7 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_centos7.tar.gz && \
           rpm -Uvh --force --nodeps *.rpm > /tmp/install_keepalived.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "7"'
  - 'ansible_distribution_release == "Core"'
  - 'ansible_distribution == "CentOS"'
  ignore_errors: true

# 中标麒麟 And CentOS7_arm64
- block:
  - name: 分发 keepalived_centos7_arm64 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_centos7_arm64.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_centos7_arm64.tar.gz"

  - name: 安装 keepalived_centos7_arm64 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_centos7_arm64.tar.gz && \
           rpm -Uvh --force --nodeps *.rpm > /tmp/install_keepalived.log 2>&1'
  when:
  - 'ansible_distribution_major_version == "7"'
  - 'ansible_distribution_release in ["AltArch","Maipo"]'
  - 'ansible_distribution in ["CentOS","RedHat"]'
  ignore_errors: true

- block:
  - name: 分发 keepalived_stretch 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_stretch.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_stretch.tar.gz"

  - name: 安装 keepalived_stretch 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_stretch.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when: ansible_distribution_release == "stretch"
  ignore_errors: true

- block:
  - name: 分发 keepalived_buster 离线包
    copy:
      src: "{{ base_dir }}/packages/keepalived_buster.tar.gz"
      dest: "/opt/kube/packages/keepalived/keepalived_buster.tar.gz"

  - name: 安装 keepalived_buster 离线包
    shell: 'cd /opt/kube/packages/keepalived && tar zxf keepalived_buster.tar.gz && \
           dpkg -i *.deb > /tmp/install_keepalived.log 2>&1'
  when: ansible_distribution_release == "buster"
  ignore_errors: true
