# 离线安装NFS 软件包
- import_tasks: offline.yml

- name: 创建nfs 目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ storage.nfs.server_path }}"

- name: 配置nfs 共享目录
  lineinfile:
    dest: /etc/exports
    line: "{{ storage.nfs.server_path }} *(rw,sync,insecure,no_subtree_check,no_root_squash)"

- name: 启动nfs 服务
  service: name={{ item }} state=restarted enabled=yes
  with_items:
  - nfs
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

- name: 启动nfs 服务
  service: name={{ item }} state=restarted enabled=yes
  with_items:
  - nfs-kernel-server
  when: 'ansible_distribution in ["Ubuntu","Debian","Kylin","uos"]'

- block:
  - name: 准备nfs-client 配置目录
    file: name={{ base_dir }}/manifests/storage/nfs state=directory

  - name: 生成nfs-client动态存储配置
    template:
      src: nfs/nfs-client-provisioner.yaml.j2
      dest: "{{ base_dir }}/manifests/storage/nfs/{{ storage.nfs.provisioner_name }}.yaml"

  - name: 开始部署nfs-client动态存储
    shell: "kubectl apply -f {{ base_dir }}/manifests/storage/nfs/{{ storage.nfs.provisioner_name }}.yaml"
  connection: local
