- import_tasks: ubuntu.yml
  when: 'ansible_distribution in ["Ubuntu","Debian","Kylin","uos","uos 20"]'

- import_tasks: centos.yml
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]' 

# 公共系统参数设置
- import_tasks: common.yml
