# 删除默认安装
- name: 删除ubuntu默认安装
  shell: "apt remove -y {{ item }}"
  with_items:
    - ufw
    - lxd
    - lxd-client
    - lxcfs
    - lxc-common
  when: 'ansible_distribution in ["Ubuntu","Debian","Kylin"]'
  ignore_errors: true

- name: 删除uos默认安装
  shell: "apt remove -y {{ item }}"
  with_items:
    - ufw
    - apache2
    - bind9
    - apache2-bin 
    - apache2-data 
    - apache2-utils 
    - libaprutil1-dbd-sqlite3 
    - libaprutil1-ldap
  when: 'ansible_distribution in ["uos","uos 20"]'
  ignore_errors: true

# 离线安装基础软件包
- import_tasks: offline.yml

- block:
  - name: 获取是否已经启动rc.local
    shell: 'systemctl status rc.local | grep Active || echo "NOT FOUND"'
    register: rc_status

  - name: fail info1
    fail: msg="Rc.local already running!"
    when: '"running" in rc_status.stdout'

  - name: 通过rc.local自启关闭 swap
    template: src=rc.local dest=/etc/rc.local mode=755

  - name: 重启 rc.local 服务
    service: name=rc.local state=restarted enabled=yes
  when: 'ansible_distribution in ["uos","uos 20"]'

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false
  when: 'ansible_distribution in ["Ubuntu","Kylin"]'

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  when: 'ansible_distribution in ["Ubuntu","Kylin"]'

# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: 准备 journal 日志相关目录
  file: name={{ item }} state=directory
  with_items:
  - "/etc/systemd/journald.conf.d"
  - "/var/log/journal"

- name: 优化设置 journal 日志
  template: src=95-k8s-journald.conf.j2 dest=/etc/systemd/journald.conf.d/95-k8s-journald.conf

- name: 重启 journald 服务
  service: name=systemd-journald state=restarted
