- name: 配置 flannel DaemonSet yaml文件
  template: src=kube-flannel-aarch64.yml.j2 dest={{ k8s_dir }}/kube-flannel.yml
  when: ansible_architecture == "aarch64"
    
- name: 配置 flannel DaemonSet yaml文件
  template: src=kube-flannel-amd64.yml.j2 dest={{ k8s_dir }}/kube-flannel.yml
  when: ansible_architecture == "x86_64"

# 只需单节点执行一次
- name: 运行 flannel网络
  shell: "kubectl apply -f {{ k8s_dir }}/kube-flannel.yml"
  run_once: true

# 等待网络插件部署成功，视下载镜像速度而定
- name: 轮询等待flannel 运行，视下载镜像速度而定
  shell: "kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' {{ inventory_hostname }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 8
  ignore_errors: true
