# 
- import_tasks: clean_kube.yml
  when: 'DEL_MASTER == "yes"'

- import_tasks: clean_lb.yml
  when: 'DEL_LB == "yes"'

- import_tasks: clean_chrony.yml
  when: 'DEL_CHRONY == "yes"'

- name: clean 'ENV PATH'
  lineinfile:
    dest: ~/.bashrc
    state: absent
    regexp: '{{ item }}'
  with_items:
  - 'helm completion'
  - 'kubectl completion'
  - 'crictl completion'
  - 'HELM_TLS_ENABLE'
  when: 'DEL_ENV == "yes"'

- name: remove files and dirs of 'ansible'
  file: name={{ item }} state=absent
  with_items:
  - "{{ base_dir }}/manifests/kube-init"
  connection: local
  run_once: true
  ignore_errors: true

- name: 重启提示 WARNNING
  debug:
    msg: "[重要]: 请重启节点以确保清除系统残留的虚拟网卡、路由信息、iptalbes|ipvs规则等 \
          [IMPORTANT]: please reboot nodes, makesure to clean out net interfaces, routes and iptables/ipvs rules"
  when: 'DEL_ETCD == "yes" and DEL_NODE == "yes" and DEL_MASTER == "yes"'
