# 离线安装K8S 软件包
- import_tasks: offline.yml

- name: enable kubelet 服务
  shell: systemctl enable kubelet
  ignore_errors: true

- name: 创建kubernetes 证书目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ k8s_dir }}"

- name: 分发kube 配置文件
  copy:
    src: "{{ base_dir }}/manifests/kube-init/{{ item }}"
    dest: "{{ k8s_dir }}/{{ item }}"
  with_items:
  - "admin.conf"

- name: 本机拷贝kube 配置文件
  shell: "rm -rf $HOME/.kube && /bin/mkdir $HOME/.kube && /bin/cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config"

- block:
  - name: 注册变量 KUBE_NODE_TOKEN_TMP
    shell: "grep -A 2 '^kubeadm join' {{ base_dir }}/manifests/kube-init/kubeadm-init.log"
    register: KUBE_NODE_TOKEN_TMP

  - name: 设置变量 KUBE_NODE_TOKEN
    set_fact: KUBE_NODE_TOKEN={{ KUBE_NODE_TOKEN_TMP.stdout }}
  connection: local

- name: 加入node 集群
  shell: "{{ KUBE_NODE_TOKEN }} | tee /etc/kubernetes/kubeadm-join.log"

- name: 添加 kubectl 命令自动补全
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'kubectl completion'
    line: 'source <(kubectl completion bash)'

- name: 设置node节点role
  shell: "kubectl label node {{ hostname|quote }} kubernetes.io/role=node --overwrite"
